### PR TITLE
fix circleci and golangci-lint

### PR DESCRIPTION
**Pull request by cw-sakamoto**

### CODE REVIEW

**Comment by cw-sakamoto** [comment]
@ada-u Hi, ada-u😄 I'm not in a hurry,,, but may I ask for a review?

ci is succeeded(https://app.circleci.com/pipelines/github/chatwork/sendgrid-stats-exporter/89/workflows/13db6982-019a-4464-8448-7cd74d28d867) but status is not changing, do you know why?

**Comment by ada-u** [comment]
@cw-sakamoto Hello! Thanks for letting me know, I will check it. ✔️

**Comment by ada-u** [comment]
📝 I forked this repo and raised PRs from the same branch.

A. `ada-u:fix_circleci_adachang` -> `chatwork:main` (https://github.com/chatwork/sendgrid-stats-exporter/pull/24)
B. `ada-u:fix_circleci_adachang` -> `ada-u:main` (https://github.com/ada-u/sendgrid-stats-exporter/pull/1)


### Hypothesis?

1. Since we can see the CI status on [B](https://github.com/ada-u/sendgrid-stats-exporter/pull/1), so I think this issue may be caused by some of repo's settings.  (but I couldn't find any CI-related settings in my repos. 🤔)

2. CircleCI seems to be suspending, but it doesn't match our situation. (https://status.circleci.com/incidents/f69gd0w5rvgk?u=gfgr07mgrrl3)

**Comment by ada-u** [comment]
@cw-sakamoto Can you confirm that the webhook has been received? 🙏 
https://support.circleci.com/hc/en-us/articles/360021511153-How-to-view-your-GitHub-webhook-deliveries?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOm51bGwsInRpY2tldF9pZCI6MTEwMzgxLCJkZWZsZWN0aW9uX2lkIjo2MTcxNTY4MzU5MDY3LCJhcnRpY2xlcyI6WzM2MDAyMTUxMTE1MywzNjAwNDQzOTU5NTMsMTE1MDEzMzUzNzQ4XSwidG9rZW4iOm51bGwsImV4cCI6MTY1NjA2MjkzNn0._6DC1OvUmpoBVftwj0VdhkgXymhk89Y5JTOmYQgPmU4

**Comment by ada-u** [comment]
@hayasshi Thanks, that might be helpful! :cw-dance:

**Comment by hayasshi** [comment]
I tried the following at CircleCI.

1. `Stop building` this repos project.
2. `Setup building` this repos project.
3. Fixed it!

Amazing power of "resting" the project.

**Comment by hayasshi** [comment]
I also enabled "Build forked pull requests" in the CircleCI project settings.

**Comment by cw-sakamoto** [comment]
@ada-u @hayasshi 
thank you for your help🥰

**Pull request merged**
